### ISSUE TITLE
Add flag for endTime offset

### ISSUE THREAD

**Issue by erikgrinaker** [frodenas/stackdriver_exporter#12]
Hi, thanks for writing stackdriver_exporter!

We use stackdriver_exporter for `loadbalancing.googleapis.com` metrics, with `monitoring.metrics-interval=5m` and Prometheus `scrape_interval: 1m`. However, Stackdriver does not register datapoints with `0` values for e.g. `https/request_count`, and this results in rarely seen time series being counted multiple times within the 5-minute interval since Stackdriver will use the most recent (old) data point. Consider the following Stackdriver result:

```json
   "metric": {
    "labels": {
     "client_country": "UNSUPPORTED",
     "response_code_class": "500",
     "protocol": "HTTP/2.0",
     "response_code": "503",
     "cache_result": "MISS",
     "proxy_continent": "Europe"
    },
    "type": "loadbalancing.googleapis.com/https/request_count"
   },
   "resource": {
    "type": "https_lb_rule",
    "labels": {
     "url_map_name": "k8s-um-default-redacted--4be62371ce9d819f",
     "backend_scope_type": "ZONE",
     "target_proxy_name": "k8s-tps-default-redacted--4be62371ce9d819f",
     "backend_target_type": "BACKEND_SERVICE",
     "project_id": "sanity-cloud",
     "backend_type": "INSTANCE_GROUP",
     "forwarding_rule_name": "k8s-fws-default-redacted--4be62371ce9d819f",
     "backend_target_name": "k8s-be-30810--4be62371ce9d819f",
     "backend_name": "k8s-ig--4be62371ce9d819f",
     "backend_scope": "europe-west1-d",
     "matched_url_path_rule": "UNMATCHED",
     "region": "global"
    }
   },
   "metricKind": "DELTA",
   "valueType": "INT64",
   "points": [
    {
     "interval": {
      "startTime": "2017-09-05T14:02:27.410Z",
      "endTime": "2017-09-05T14:03:27.410Z"
     },
     "value": {
      "int64Value": "18"
     }
    },
    {
     "interval": {
      "startTime": "2017-09-05T14:00:27.410Z",
      "endTime": "2017-09-05T14:01:27.410Z"
     },
     "value": {
      "int64Value": "13"
     }
    },
    {
     "interval": {
      "startTime": "2017-09-05T13:59:27.410Z",
      "endTime": "2017-09-05T14:00:27.410Z"
     },
     "value": {
      "int64Value": "84"
     }
    }
```

This time series does not have any data points for the intervals 14:01:27-14:02:27 and 14:03:27-14:04:27 because there were no requests matching this time series in these intervals. Thus, when Prometheus scrapes at e.g. 14:02:30 and 14:04:30, it will use the old values (13 and 18) rather than the correct values of 0. This results in our request graphs showing roughly 30% more traffic than there really is.

We could avoid this by setting `monitoring.metrics-interval=1m` - however, if Google has any amount of latency between measuring and publishing a value, then data points may be lost since the old value could be older than 1m while the new value is not yet published. We could adjust for this by setting e.g. `monitoring.metrics-interval=1m20s` so that we read the previous data point in these cases, but that could double-count the old value if the new value is 0 and thus not recorded at all.

I think the correct solution would be to add a flag `monitoring.metrics-offset` or `monitoring.metrics-delay` which adjusts `startTime` and (more importantly) `endTime` backwards in time. Thus, by setting `monitoring.metrics-interval=1m` and `monitoring.metrics-offset=20s`, it would fetch data points in the 1-minute interval up until 20 seconds ago. This would only fetch a single data point (if any), and would allow for 20 seconds of latency in Stackdriver publishing the data point.

**Comment by frodenas** [comment]
@erikgrinaker [v0.4.0](https://github.com/frodenas/stackdriver_exporter/releases/tag/v0.4.0) contains your PR.

**Comment by erikgrinaker** [comment]
Great, thanks @frodenas !
