### ISSUE TITLE
GCS metrics missing

### ISSUE THREAD

**Issue by atombender** [frodenas/stackdriver_exporter#14]
Running 0.4.0 with:

```
STACKDRIVER_EXPORTER_MONITORING_METRICS_INTERVAL=1m
STACKDRIVER_EXPORTER_MONITORING_METRICS_OFFSET=2m
STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES=loadbalancing.googleapis.com,storage.googleapis.com
```

I get loadbalancing stats, but no storage stats. Actually, at one point I *did* get a single sample — if I graph over 24 hours, it sometimes shows up, then disappears, presumably due to how Prometheus handles interpolation. This implies there was just one data point.

After doing some digging with the API, it seems StackDriver only returns GCS data if you give it an interval >= 24 hours. If you give it anything less, no metrics are returned at all. This includes, say, `metric.type="storage.googleapis.com/api/request_count"`. For example, this URL returns data (24 hours):

```
https://monitoring.googleapis.com/v3/projects/my-project-name/timeSeries?filter=metric.type%3D%22storage.googleapis.com%2Fapi%2Frequest_count%22&interval.endTime=2017-09-07T14%3A34%3A33-04%3A00&interval.startTime=2017-09-06T14%3A34%3A33-04%3A00
```

This does not (5 minutes):

```
https://monitoring.googleapis.com/v3/projects/my-project-name/timeSeries?filter=metric.type%3D%22storage.googleapis.com%2Fapi%2Frequest_count%22&interval.endTime=2017-09-07T14%3A34%3A33-04%3A00&interval.startTime=2017-09-07T14%3A29%3A33-04%3A00
```

This implies that StackDriver granularity is such that some data points are only collected every 24 hours. (Which seems weird for a delta metric called `request_count`!) AWS CloudWatch metrics coincidentally work the same way. But I can't find anything in the StackDriver documentation about certain data points only being available at certain granularities.

The solution would be to vary the monitoring interval depending on what group of stats is collected, but that'd also require that we know the granularity of each metric.

**Comment by frodenas** [comment]
You can run 2 stackdriver exporters, each one with different metric prefixes and therefore, with different metric's intervals & offsets, and configure prometheus to scrape both exporters.
