### ISSUE TITLE
Dockerhub image 

### ISSUE THREAD

**Issue by SqiSch** [frodenas/stackdriver_exporter#16]
Hei, 
it would be nice to have an dockerhub image of for this exporter. Is there an reason why you don´t have one?

Regards, 
Marcel

**Comment by frodenas** [comment]
It's already there: [frodenas/stackdriver-exporter](https://hub.docker.com/r/frodenas/stackdriver-exporter/). Instructions at the [README](https://github.com/frodenas/stackdriver_exporter#docker).

**Comment by SqiSch** [comment]
Hhihi.. 
I don´t know why i didn´t have seen it in the Readme. Thx for that.
