### ISSUE TITLE
how to read stackdriver metrics without k8s cluster in the same project

### ISSUE THREAD

**Issue by wleese** [frodenas/stackdriver_exporter#17]
I was wondering if I have my resources such as pubsub in project A but my kubernetes cluster in project B, if it's possible to have stackdriver_exporter in project A access stackdriver in project B?

**Comment by frodenas** [comment]
Yes, you can run the stackdriver_exporter wherever you want (ie. on your laptop), the only thing you will need is access to the stackdriver api by providing the `google.project-id` and the project credentials.

**Comment by wleese** [comment]
Thanks!
