### ISSUE TITLE
Export support other metrics different at Compute?

### ISSUE THREAD

**Issue by cdgraff** [frodenas/stackdriver_exporter#18]
Hi @frodenas , i'm running the exporter with this params:
`
docker run -p 9265:9255 frodenas/stackdriver-exporter -google.project-id my-project -monitoring.metrics-type-prefixes "bigquery.googleapis.com,compute.googleapis.com" -log.level debug`

I run on debug log level, and saw the call to BigQuery metrics:
```
time="2017-12-27T15:20:07Z" level=debug msg="Listing Google Stackdriver Monitoring metric descriptors starting with `compute.googleapis.com`..." source="monitoring_collector.go:210" 
time="2017-12-27T15:20:07Z" level=debug msg="Listing Google Stackdriver Monitoring metric descriptors starting with `bigquery.googleapis.com`..." source="monitoring_collector.go:210" 

```

Example of one call from bigquery that i'm sure that have metrics:
```
time="2017-12-27T15:11:57Z" level=debug msg="Retrieving Google Stackdriver Monitoring metrics for descriptor `bigquery.googleapis.com/query/count`.
.." source="monitoring_collector.go:166" 
```

But into **/metrics**, don't have any referente to this values

Is this metrics supported? I saw similar issue with any other metrics different to "compute".

thanks!

**Comment by frodenas** [comment]
@cdgraff Try increasing the `monitoring.metrics-interval`. Some Stackdriver metrics have latency and might happen that the time-series do NOT contain any data point at the default `5m` interval.

**Comment by cdgraff** [comment]
thanks! that works!!! and BTW; if this happens to others, reminder to enabled StackDriver monitoring too :( Compute was by default but BigQuery and others possible not has Stats if you don't import into Stackdriver.
