### ISSUE TITLE
push Docker release image

### ISSUE THREAD

**Issue by julianvmodesto** [frodenas/stackdriver_exporter#2]
Would be great to push to Docker Hub and/or Quay at least manually at first, and then maybe automatically (as in as in https://github.com/prometheus/haproxy_exporter/commit/22abef333ec6c0335d5de552d35a8893e389f0cb) so users can run this in Docker and by extension Kubernetes, etc.

**Comment by frodenas** [comment]
Docker image available at [frodenas/stackdriver-exporter](https://hub.docker.com/r/frodenas/stackdriver-exporter/tags/):

```
$ docker run -p 9255:9255 frodenas/stackdriver-exporter <flags>
```
