### ISSUE TITLE
cloudsql, data scraping  inconsistancy

### ISSUE THREAD

**Issue by helldrum** [frodenas/stackdriver_exporter#32]
Hello,
I am experiencing the same problem with cloudsql databases.
my use case is to know when my database are not up.

can you please tell me how can i setup the exporter in order to have the current status ?

if i setup the offset to 24h, i have the database status of 24h, 
and metric stackdriver_cloudsql_database_cloudsql_googleapis_com_database_uptime alway return 60

(my databases exist and are up since Jun 21, 2018, 5:01:07 PM  )

news databases and recent stop start actions are not return by the exporter
 

if i setup the exporter this way, i don't have any cloudsql metrics
```
STACKDRIVER_EXPORTER_MONITORING_METRICS_INTERVAL: '3m'
STACKDRIVER_EXPORTER_MONITORING_METRICS_OFFSET '1s'
STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES=cloudsql.googleapis.com/database/up
```
if i stop an existing database and wait for the scaping timing , exporter make more time to respond, but don't display metrics
if i start the database i previouly stopped metrics are not displayed too. 

Can you please tell me what i'am doing wrong ?
How can i setup the exporter in order to get current database status as it available in stackdriver metrics GUI (minus the prometheus scraping interval ) ?

kubernete version is 1.10.4-gke.2 , i don't use helm in my case (static configuration)
image exporter version is frodenas/stackdriver-exporter:v0.5.1

Thank you for your help

**Comment by yanc0** [comment]
Hi @helldrum,

I'm sorry but I cannot reproduce your issue. Here is my configuration:

```
$ ./stackdriver_exporter --google.project-id my-project \
                         --monitoring.metrics-type-prefixes "cloudsql.googleapis.com/database/up" &

$ curl http://localhost:9255/metrics | grep "database_up\{"
stackdriver_cloudsql_database_cloudsql_googleapis_com_database_up{database_id="my-project:db1",project_id="my-project",region="europe",unit="1"} 1
stackdriver_cloudsql_database_cloudsql_googleapis_com_database_up{database_id="my-project:db2",project_id="my-project",region="europe",unit="1"} 1
stackdriver_cloudsql_database_cloudsql_googleapis_com_database_up{database_id="my-project:db3",project_id="my-project",region="europe",unit="1"} 1
```

Stackdriver Exporter is exporting metrics well on my machine. Are you looking for this kind of output above?

**Comment by helldrum** [comment]
Hello @yanc0,
I realize I misunderstand how the exporter works.

the properties
```
STACKDRIVER_EXPORTER_MONITORING_METRICS_OFFSET
 STACKDRIVER_EXPORTER_MONITORING_METRICS_INTERVAL
```
are not mandatory and if I simply don't use it I have the desired behavior.
I can now manage my databases state
Thanks for your help

Regards,
Helldrum
