### ISSUE TITLE
Support for metric wildcards

### ISSUE THREAD

**Issue by elsbrock** [frodenas/stackdriver_exporter#63]
I have noticed that stackdriver exporter requests the lists of metrics at some point; it'd be great to be able to specify the list of metrics via wildcard instead of each of them explicity, e.g. `compute.googleapis.com/*`.

**Comment by dcaba** [comment]
Id say @elsbrock that if you just specify a prefix, yeah, it lists and fetches everything. Is that not the case in your example?

**Comment by elsbrock** [comment]
It does? I never tried it, just used the above expression and that did not work. I will try it out later. Thanks!

**Comment by elsbrock** [comment]
I can confirm this works. Should the README maybe enhanced with this info?

**Comment by dcaba** [comment]
You are right: maybe another example here: https://github.com/frodenas/stackdriver_exporter#example , maybe pointing out how to import all k8s/nodes related metrics ("kubernetes.io/node/", https://cloud.google.com/monitoring/api/metrics_kubernetes), could facilitate the understanding of that functionality. I think @frodenas is not very active now in this project, but feel free to submit a PR for that!
