### ISSUE TITLE
Missing metrics

### ISSUE THREAD

**Issue by kinghrothgar** [frodenas/stackdriver_exporter#7]
I read #3 but I don't understand why I'm not seeing some metrics. I am scraping stackdriver_exporter every 15s and stackdriver_exporter is scraping Google every 30s. As such I wouldn't think I would be missing any metrics regardless of how often Google returns them. I don't see several of them however. I'm telling it to scrape all `bigtable.googleapis.com`. When I try to graph `stackdriver_monitoring_bigtable_googleapis_com_cluster_cpu_load` in prometheus after several hours it still has no data for that metric.

**Comment by frodenas** [comment]
Details please?

**Comment by frodenas** [comment]
When you say "_stackdriver_exporter is scraping Google every 30s_" I guess you mean that you're setting the `monitoring.metrics-interval` flag to `30s` right? If yes, can you please increase this interval to ie `5m`? That flag specifies the metric's timestamp interval to request, not the interval when to scrape Stackdriver.

The `stackdriver_exporter` is just a proxy, it does NOT store metrics. Every time `prometheus` scrapes the exporter, the exporter requests Stackdriver API for the metric's time-series that contain data points in a specific interval. That interval is from the request's time back to the (request time - `monitoring.metrics-interval`). 

Metrics in Stackdriver have some [latency](https://cloud.google.com/monitoring/api/v3/metrics#latency), and If you specify a low `monitoring.metrics-interval`, might happen that the time-series do NOT contain any data point at that interval. For example, the BigTable `Cluster CPU Load` is gathered by Stackdriver every 60s (`t1`) and the exporter is set with a `metrics-interval` of `30s`, if the scrape happens at `t1+31s` then the exporter will NOT gather any data point.

**Comment by kinghrothgar** [comment]
Aaahh. That makes much more sense. Would you accept a PR that adds clarification to that option in the documentation?

**Comment by frodenas** [comment]
Sure!

**Comment by kinghrothgar** [comment]
To piggy back on this, does metrics-interval also happen to specify the interval the DELTA metrics are over? I haven't been able to decern what the interval is for Stackdriver DELTA metrics from Google's docs.

**Comment by frodenas** [comment]
I don't think so, but I'm unsure. To me, the DELTA comes from the source metric (delta between 2 consecutive data points gathered from the Stackdriver agent).

**Comment by frodenas** [comment]
I'm closing this issue, but feel free to reopen or comment if you still have more doubts.
